name: C/C++ CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xyrisos/xyris-build/xyris-build:3.4.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    # Unit Tests
    - name: Build and Run Tests
      run: make unit-test && ./Distribution/unit-test -r junit --out ./Tests/report.xml
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      with:
        fail_on_failure: true
        report_paths: 'Tests/report.xml'
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: Tests/report.xml
    # Debug
    - name: 'Build Kernel (Debug)'
      run: make MODE=debug
    - name: 'Build Image (Debug)'
      run: make dist MODE=debug
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: os-image-debug
        path: Distribution/debug/xyris.img
    # Release
    - name: 'Build Kernel (Release)'
      run: make MODE=release
    - name: 'Build Image (Release)'
      run: make dist MODE=release
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: os-image-release
        path: Distribution/release/xyris.img
